In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 5000)
pd.options.display.max_rows = 4000

In [2]:
data_total = pd.read_csv('~/ga/projects/capstone_data/data/total.csv')

In [3]:
data_total.head()

,ITIN_ID,MKT_ID,SEQ_NUM,COUPONS,YEAR,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,QUARTER,ORIGIN,ORIGIN_COUNTRY,ORIGIN_STATE_FIPS,ORIGIN_STATE_ABR,ORIGIN_STATE_NM,ORIGIN_WAC,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST,DEST_COUNTRY,DEST_STATE_FIPS,DEST_STATE_ABR,DEST_STATE_NM,DEST_WAC,TRIP_BREAK,COUPON_TYPE,TICKET_CARRIER,OPERATING_CARRIER,REPORTING_CARRIER,PASSENGERS,FARE_CLASS,DISTANCE,DISTANCE_GROUP,GATEWAY,ITIN_GEO_TYPE,COUPON_GEO_TYPE,Unnamed: 36
0,201846,20184601,1,1,2018,10135,1013505,30135,4,ABE,US,42,PA,Pennsylvania,23,10397,1039707,30397,ATL,US,13,GA,Georgia,34,X,A,DL,9E,9E,1.0,Y,692.0,2,0.0,2,2,NaN
1,201847,20184701,1,1,2018,10135,1013505,30135,4,ABE,US,42,PA,Pennsylvania,23,10397,1039707,30397,ATL,US,13,GA,Georgia,34,X,A,DL,9E,9E,1.0,X,692.0,2,0.0,2,2,NaN
2,201848,20184801,1,1,2018,10135,1013505,30135,4,ABE,US,42,PA,Pennsylvania,23,10397,1039707,30397,ATL,US,13,GA,Georgia,34,X,A,DL,9E,9E,3.0,X,692.0,2,0.0,2,2,NaN
3,201849,20184901,1,1,2018,10135,1013505,30135,4,ABE,US,42,PA,Pennsylvania,23,10397,1039707,30397,ATL,US,13,GA,Georgia,34,X,A,DL,9E,9E,1.0,X,692.0,2,0.0,2,2,NaN
4,2018410,201841001,1,1,2018,10135,1013505,30135,4,ABE,US,42,PA,Pennsylvania,23,10397,1039707,30397,ATL,US,13,GA,Georgia,34,X,A,DL,9E,9E,1.0,X,692.0,2,0.0,2,2,NaN

In [4]:
data_total.columns

Index(['ITIN_ID', 'MKT_ID', 'SEQ_NUM', 'COUPONS', 'YEAR', 'ORIGIN_AIRPORT_ID',
       'ORIGIN_AIRPORT_SEQ_ID', 'ORIGIN_CITY_MARKET_ID', 'QUARTER', 'ORIGIN',
       'ORIGIN_COUNTRY', 'ORIGIN_STATE_FIPS', 'ORIGIN_STATE_ABR',
       'ORIGIN_STATE_NM', 'ORIGIN_WAC', 'DEST_AIRPORT_ID',
       'DEST_AIRPORT_SEQ_ID', 'DEST_CITY_MARKET_ID', 'DEST', 'DEST_COUNTRY',
       'DEST_STATE_FIPS', 'DEST_STATE_ABR', 'DEST_STATE_NM', 'DEST_WAC',
       'TRIP_BREAK', 'COUPON_TYPE', 'TICKET_CARRIER', 'OPERATING_CARRIER',
       'REPORTING_CARRIER', 'PASSENGERS', 'FARE_CLASS', 'DISTANCE',
       'DISTANCE_GROUP', 'GATEWAY', 'ITIN_GEO_TYPE', 'COUPON_GEO_TYPE',
       'Unnamed: 36'],
      dtype='object')

In [5]:
data_total = data_total[['ORIGIN', 'ORIGIN_STATE_ABR','DEST',  'DEST_STATE_ABR','TICKET_CARRIER', 'OPERATING_CARRIER',
       'REPORTING_CARRIER', 'PASSENGERS','DISTANCE']]

In [6]:
new_columns = [column.lower() for column in data_total.columns]
data_total.columns = new_columns

In [7]:
data_total.head()

,origin,origin_state_abr,dest,dest_state_abr,ticket_carrier,operating_carrier,reporting_carrier,passengers,distance
0,ABE,PA,ATL,GA,DL,9E,9E,1.0,692.0
1,ABE,PA,ATL,GA,DL,9E,9E,1.0,692.0
2,ABE,PA,ATL,GA,DL,9E,9E,3.0,692.0
3,ABE,PA,ATL,GA,DL,9E,9E,1.0,692.0
4,ABE,PA,ATL,GA,DL,9E,9E,1.0,692.0

In [9]:
data_total.shape

(10794583, 9)

In [10]:
data_oct = pd.read_csv('~/ga/projects/capstone_data/data/october.csv')

/Users/ilyakvyatkovskiy/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [11]:
data_oct.head()

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_FIPS,ORIGIN_STATE_NM,ORIGIN_WAC,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST,DEST_CITY_NAME,DEST_STATE_ABR,DEST_STATE_FIPS,DEST_STATE_NM,DEST_WAC,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,DEP_DELAY_GROUP,DEP_TIME_BLK,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,ARR_DELAY_GROUP,ARR_TIME_BLK,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,FLIGHTS,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,FIRST_DEP_TIME,TOTAL_ADD_GTIME,LONGEST_ADD_GTIME,DIV_AIRPORT_LANDINGS,DIV_REACHED_DEST,DIV_ACTUAL_ELAPSED_TIME,DIV_ARR_DELAY,DIV_DISTANCE,DIV1_AIRPORT,DIV1_AIRPORT_ID,DIV1_AIRPORT_SEQ_ID,DIV1_WHEELS_ON,DIV1_TOTAL_GTIME,DIV1_LONGEST_GTIME,DIV1_WHEELS_OFF,DIV1_TAIL_NUM,DIV2_AIRPORT,DIV2_AIRPORT_ID,DIV2_AIRPORT_SEQ_ID,DIV2_WHEELS_ON,DIV2_TOTAL_GTIME,DIV2_LONGEST_GTIME,DIV2_WHEELS_OFF,DIV2_TAIL_NUM,DIV3_AIRPORT,DIV3_AIRPORT_ID,DIV3_AIRPORT_SEQ_ID,DIV3_WHEELS_ON,DIV3_TOTAL_GTIME,DIV3_LONGEST_GTIME,DIV3_WHEELS_OFF,DIV3_TAIL_NUM,DIV4_AIRPORT,DIV4_AIRPORT_ID,DIV4_AIRPORT_SEQ_ID,DIV4_WHEELS_ON,DIV4_TOTAL_GTIME,DIV4_LONGEST_GTIME,DIV4_WHEELS_OFF,DIV4_TAIL_NUM,DIV5_AIRPORT,DIV5_AIRPORT_ID,DIV5_AIRPORT_SEQ_ID,DIV5_WHEELS_ON,DIV5_TOTAL_GTIME,DIV5_LONGEST_GTIME,DIV5_WHEELS_OFF,DIV5_TAIL_NUM,Unnamed: 109
0,2018,4,10,1,1,2018-10-01,WN,19393,WN,N221WN,802,10140,1014005,30140,ABQ,"Albuquerque, NM",NM,35,New Mexico,86,10821,1082106,30852,BWI,"Baltimore, MD",MD,24,Maryland,35,905,903.0,-2.0,0.0,0.0,-1.0,0900-0959,10.0,913.0,1430.0,3.0,1450,1433.0,-17.0,0.0,0.0,-2.0,1400-1459,0.0,NaN,0.0,225.0,210.0,197.0,1.0,1670.0,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018,4,10,1,1,2018-10-01,WN,19393,WN,N8329B,3744,10140,1014005,30140,ABQ,"Albuquerque, NM",NM,35,New Mexico,86,10821,1082106,30852,BWI,"Baltimore, MD",MD,24,Maryland,35,1500,1458.0,-2.0,0.0,0.0,-1.0,1500-1559,8.0,1506.0,2017.0,3.0,2045,2020.0,-25.0,0.0,0.0,-2.0,2000-2059,0.0,NaN,0.0,225.0,202.0,191.0,1.0,1670.0,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2018,4,10,1,1,2018-10-01,WN,19393,WN,N920WN,1019,10140,1014005,30140,ABQ,"Albuquerque, NM",NM,35,New Mexico,86,11259,1125904,30194,DAL,"Dallas, TX",TX,48,Texas,74,1800,1802.0,2.0,2.0,0.0,0.0,1800-1859,7.0,1809.0,2029.0,3.0,2045,2032.0,-13.0,0.0,0.0,-1.0,2000-2059,0.0,NaN,0.0,105.0,90.0,80.0,1.0,580.0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018,4,10,1,1,2018-10-01,WN,19393,WN,N480WN,1499,10140,1014005,30140,ABQ,"Albuquerque, NM",NM,35,New Mexico,86,11259,1125904,30194,DAL,"Dallas, TX",TX,48,Texas,74,950,947.0,-3.0,0.0,0.0,-1.0,0900-0959,12.0,959.0,1220.0,3.0,1235,1223.0,-12.0,0.0,0.0,-1.0,1200-1259,0.0,NaN,0.0,105.0,96.0,81.0,1.0,580.0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018,4,10,1,1,2018-10-01,WN,19393,WN,N227WN,3635,10140,1014005,30140,ABQ,"Albuquerque, NM",NM,35,New Mexico,86,11259,1125904,30194,DAL,"Dallas, TX",TX,48,Texas,74,1150,1151.0,1.0,1.0,0.0,0.0,1100-1159,11.0,1202.0,1422.0,1.0,1430,1423.0,-7.0,0.0,0.0,-1.0,1400-1459,0.0,NaN,0.0,100.0,92.0,80.0,1.0,580.0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
data_oct.columns

Index(['YEAR', 'QUARTER', 'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'FL_DATE',
       'OP_UNIQUE_CARRIER', 'OP_CARRIER_AIRLINE_ID', 'OP_CARRIER', 'TAIL_NUM',
       ...
       'DIV4_TAIL_NUM', 'DIV5_AIRPORT', 'DIV5_AIRPORT_ID',
       'DIV5_AIRPORT_SEQ_ID', 'DIV5_WHEELS_ON', 'DIV5_TOTAL_GTIME',
       'DIV5_LONGEST_GTIME', 'DIV5_WHEELS_OFF', 'DIV5_TAIL_NUM',
       'Unnamed: 109'],
      dtype='object', length=110)

In [13]:
data_oct.shape

(616101, 110)

In [14]:
data_oct['CANCELLED'].value_counts()

0.0    611616
1.0      4485
Name: CANCELLED, dtype: int64

In [15]:
data_oct['DIVERTED'].value_counts()

0.0    614819
1.0      1282
Name: DIVERTED, dtype: int64

In [16]:
data_oct['FLIGHTS'].value_counts()

1.0    616101
Name: FLIGHTS, dtype: int64

In [17]:
data_oct['CARRIER_DELAY'].value_counts()

0.0       54028
1.0        1960
2.0        1889
3.0        1809
6.0        1743
4.0        1734
5.0        1632
7.0        1559
8.0        1419
15.0       1269
9.0        1258
10.0       1156
16.0       1154
11.0       1056
17.0       1043
18.0       1000
12.0        996
19.0        976
14.0        955
13.0        945
20.0        879
21.0        743
22.0        731
23.0        683
24.0        616
26.0        607
25.0        544
27.0        539
29.0        484
30.0        468
28.0        461
32.0        415
31.0        399
33.0        393
35.0        374
34.0        362
36.0        352
38.0        335
37.0        327
39.0        317
41.0        295
40.0        288
44.0        274
43.0        250
42.0        238
46.0        234
47.0        234
45.0        224
48.0        219
49.0        199
53.0        196
50.0        181
54.0        175
55.0        173
52.0        168
51.0        162
56.0        156
57.0        150
60.0        149
59.0        147
66.0        144
67.0        142
62.0        138
61.0        138
58.0        137
63.0        135
65.0        132
64.0        125
68.0        118
70.0        116
80.0        111
69.0        111
72.0        103
71.0        100
75.0         98
76.0         96
86.0         95
74.0         95
73.0         91
83.0         89
77.0         88
78.0         86
81.0         86
79.0         85
91.0         85
84.0         84
88.0         78
87.0         77
82.0         76
95.0         73
90.0         72
100.0        72
98.0         71
89.0         70
112.0        67
85.0         67
99.0         65
93.0         64
102.0        64
96.0         64
92.0         63
94.0         63
105.0        62
97.0         61
109.0        56
101.0        55
103.0        55
119.0        54
114.0        53
106.0        53
122.0        52
113.0        50
117.0        49
111.0        47
118.0        46
104.0        45
108.0        43
107.0        43
116.0        42
110.0        40
128.0        40
125.0        40
127.0        39
123.0        39
143.0        38
133.0        37
115.0        37
121.0        36
129.0        35
126.0        35
135.0        34
120.0        32
148.0        31
132.0        31
134.0        31
124.0        30
139.0        30
155.0        30
141.0        30
142.0        29
138.0        29
150.0        29
130.0        28
145.0        28
153.0        27
162.0        26
154.0        25
131.0        25
144.0        24
168.0        24
136.0        24
137.0        24
146.0        24
177.0        24
183.0        23
169.0        23
149.0        22
140.0        22
147.0        21
157.0        20
161.0        20
170.0        20
163.0        20
166.0        20
160.0        19
179.0        19
182.0        19
181.0        18
152.0        18
178.0        18
164.0        18
172.0        17
167.0        17
158.0        17
151.0        17
173.0        16
171.0        16
188.0        16
165.0        15
201.0        15
204.0        15
261.0        15
159.0        15
208.0        14
187.0        14
207.0        14
193.0        14
156.0        14
192.0        13
195.0        13
220.0        13
226.0        13
200.0        13
196.0        13
194.0        12
248.0        12
203.0        12
174.0        12
213.0        12
211.0        12
184.0        12
233.0        12
190.0        11
217.0        11
231.0        11
209.0        10
175.0        10
180.0        10
228.0        10
221.0        10
243.0        10
176.0        10
197.0         9
189.0         9
186.0         9
212.0         9
199.0         9
252.0         9
218.0         9
225.0         9
227.0         9
185.0         8
278.0         8
205.0         8
306.0         8
229.0         8
269.0         8
266.0         8
210.0         8
214.0         8
240.0         8
223.0         8
257.0         8
224.0         8
272.0         8
295.0         7
250.0         7
234.0         7
235.0         7
238.0         7
264.0         7
293.0         7
245.0         7
247.0         7
256.0         7
230.0         7
284.0         7
285.0         7
258.0         7
330.0         7
283.0         6
191.0         6
253.0         6
292.0         6
198.0         6
308.0         6
254.0         6
277.0         6
241.0         6
271.0         6
202.0         6
236.0         6
288.0         6
280.0         6
386.0         6
309.0         6
219.0         6
326.0         6
206.0         6
260.0         5
255.0         5
282.0         5
342.0         5
242.0         5
251.0         5
313.0         5
267.0         5
239.0         5
237.0         5
299.0         5
244.0         5
274.0         5
262.0         5
273.0         5
296.0         5
263.0         5
350.0         5
216.0         5
300.0         5
286.0         4
403.0         4
312.0         4
410.0         4
325.0         4
357.0         4
279.0         4
871.0         4
215.0         4
354.0         4
270.0         4
287.0         4
425.0         4
304.0         4
423.0         4
249.0         4
477.0         4
412.0         4
393.0         4
318.0         4
232.0         4
222.0         4
315.0         4
335.0         4
298.0         4
332.0         4
536.0         3
837.0         3
485.0         3
465.0         3
377.0         3
371.0         3
265.0         3
349.0         3
394.0         3
624.0         3
643.0         3
355.0         3
336.0         3
379.0         3
454.0         3
784.0         3
475.0         3
329.0         3
358.0         3
246.0         3
540.0         3
566.0         3
816.0         3
344.0         3
323.0         3
531.0         3
303.0         3
356.0         3
339.0         3
305.0         3
340.0         3
547.0         3
297.0         3
343.0         3
341.0         3
331.0         3
406.0         3
637.0         2
316.0         2
903.0         2
502.0         2
397.0         2
367.0         2
667.0         2
721.0         2
496.0         2
446.0         2
428.0         2
851.0         2
395.0         2
366.0         2
527.0         2
443.0         2
468.0         2
363.0         2
301.0         2
470.0         2
438.0         2
372.0         2
310.0         2
649.0         2
788.0         2
458.0         2
322.0         2
869.0         2
716.0         2
430.0         2
390.0         2
352.0         2
426.0         2
319.0         2
281.0         2
311.0         2
882.0         2
381.0         2
317.0         2
739.0         2
429.0         2
389.0         2
385.0         2
334.0         2
378.0         2
417.0         2
436.0         2
603.0         2
328.0         2
376.0         2
759.0         2
275.0         2
259.0         2
581.0         2
1035.0        2
402.0         2
495.0         2
511.0         2
856.0         2
579.0         2
549.0         2
472.0         2
416.0         2
364.0         2
785.0         2
435.0         2
786.0         2
440.0         2
405.0         2
290.0         2
441.0         2
407.0         2
433.0         2
534.0         2
368.0         2
362.0         2
561.0         2
678.0         2
351.0         2
346.0         2
497.0         2
294.0         2
456.0         2
541.0         2
291.0         2
982.0         2
481.0         2
888.0         1
932.0         1
687.0         1
682.0         1
776.0         1
717.0         1
442.0         1
808.0         1
484.0         1
673.0         1
709.0         1
679.0         1
445.0         1
431.0         1
707.0         1
681.0         1
705.0         1
713.0         1
698.0         1
661.0         1
388.0         1
460.0         1
449.0         1
658.0         1
451.0         1
654.0         1
1000.0        1
434.0         1
528.0         1
455.0         1
796.0         1
545.0         1
572.0         1
494.0         1
550.0         1
551.0         1
676.0         1
553.0         1
554.0         1
491.0         1
558.0         1
490.0         1
559.0         1
404.0         1
563.0         1
486.0         1
565.0         1
483.0         1
542.0         1
539.0         1
1822.0        1
537.0         1
792.0         1
513.0         1
514.0         1
904.0         1
517.0         1
518.0         1
519.0         1
505.0         1
521.0         1
1040.0        1
523.0         1
525.0         1
2109.0        1
499.0         1
529.0         1
498.0         1
533.0         1
396.0         1
482.0         1
574.0         1
1248.0        1
614.0         1
615.0         1
463.0         1
618.0         1
462.0         1
622.0         1
924.0         1
461.0         1
626.0         1
392.0         1
408.0         1
629.0         1
459.0         1
634.0         1
1012.0        1
639.0         1
457.0         1
466.0         1
611.0         1
610.0         1
1714.0        1
577.0         1
912.0         1
800.0         1
582.0         1
585.0         1
480.0         1
320.0         1
474.0         1
609.0         1
896.0         1
601.0         1
602.0         1
605.0         1
606.0         1
607.0         1
469.0         1
595.0         1
839.0         1
704.0         1
532.0         1
1025.0        1
353.0         1
1047.0        1
1051.0        1
1055.0        1
1065.0        1
876.0         1
347.0         1
1022.0        1
1082.0        1
756.0         1
628.0         1
516.0         1
345.0         1
1105.0        1
360.0         1
512.0         1
736.0         1
1373.0        1
361.0         1
872.0         1
728.0         1
949.0         1
954.0         1
961.0         1
962.0         1
963.0         1
348.0         1
1003.0        1
359.0         1
852.0         1
991.0         1
1431.0        1
993.0         1
995.0         1
997.0         1
1111.0        1
1114.0        1
942.0         1
1235.0        1
302.0         1
1210.0        1
338.0         1
1172.0        1
337.0         1
307.0         1
1338.0        1
314.0         1
1205.0        1
1335.0        1
333.0         1
1282.0        1
321.0         1
1303.0        1
327.0         1
640.0         1
1206.0        1
1202.0        1
276.0         1
1158.0        1
1124.0        1
508.0         1
1135.0        1
1145.0        1
1363.0        1
1154.0        1
289.0         1
1166.0        1
1353.0        1
632.0         1
1169.0        1
432.0         1
1179.0        1
1392.0        1
500.0         1
1168.0        1
952.0         1
933.0         1
731.0         1
398.0         1
778.0         1
380.0         1
794.0         1
656.0         1
799.0         1
768.0         1
803.0         1
805.0         1
828.0         1
809.0         1
810.0         1
268.0         1
813.0         1
818.0         1
819.0         1
822.0         1
777.0         1
770.0         1
826.0         1
415.0         1
427.0         1
734.0         1
1060.0        1
743.0         1
421.0         1
750.0         1
419.0         1
757.0         1
940.0         1
758.0         1
414.0         1
761.0         1
765.0         1
766.0         1
409.0         1
769.0         1
823.0         1
492.0         1
931.0         1
902.0         1
885.0         1
887.0         1
889.0         1
895.0         1
374.0         1
898.0         1
373.0         1
1478.0        1
382.0         1
369.0         1
914.0         1
915.0         1
919.0         1
925.0         1
365.0         1
648.0         1
883.0         1
879.0         1
830.0         1
861.0         1
391.0         1
838.0         1
1558.0        1
836.0         1
772.0         1
855.0         1
858.0         1
862.0         1
720.0         1
1537.0        1
865.0         1
867.0         1
870.0         1
944.0         1
383.0         1
874.0         1
568.0         1
Name: CARRIER_DELAY, dtype: int64

In [18]:
data_oct['DIV_AIRPORT_LANDINGS'].value_counts()

0    614762
1      1270
9        57
2        12
Name: DIV_AIRPORT_LANDINGS, dtype: int64

In [19]:
data_oct['DIV_REACHED_DEST'].value_counts()

1.0    1137
0.0     145
Name: DIV_REACHED_DEST, dtype: int64

In [20]:
data_oct['ARR_DEL15'].value_counts()

0.0    508677
1.0    101657
Name: ARR_DEL15, dtype: int64

In [21]:
data_nov = pd.read_csv('~/ga/projects/capstone_data/data/november.csv')

/Users/ilyakvyatkovskiy/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (48,69,76,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [22]:
data_dec = pd.read_csv('~/ga/projects/capstone_data/data/december.csv')

In [23]:
data_nov.shape

(586178, 110)

In [24]:
data_dec.shape

(593842, 110)

In [25]:
data_oct.shape[0]+data_nov.shape[0]+data_dec.shape[0]

1796121

In [26]:
data_oct['OP_CARRIER'].value_counts()

WN    114663
DL     82134
AA     78963
OO     66562
UA     55565
YX     26882
MQ     26147
B6     24923
OH     23969
AS     21634
9E     20943
YV     19306
EV     15358
NK     13780
F9     10516
G4      7597
HA      7159
Name: OP_CARRIER, dtype: int64

In [ ]:
delays = pd.concat([data_oct,data_nov,data_dec])